spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tontinepro_db
    username: tontinepro_user
    password: tontinepro_pass
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      connection-timeout: 30000

  data:
    redis:
      host: localhost
      port: 6379
      # pas de mot de passe sur le Redis de dev

  jpa:
    properties:
      hibernate:
        format_sql: true

  mail:
    host: localhost
    port: 1025
    properties:
      mail.smtp.auth: false
      mail.smtp.starttls.enable: false

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
